os: osx
language: objective-c  #1
osx_image: xcode8.3 #2
xcode_project: glink.xcodeproj #3
xcode_scheme: glink #4
xcode_sdk: iphonesimulator10.3 #5
git:
  depth: 3

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - development